### PR TITLE
Remove unused methods and query parameters

### PR DESCRIPTION
**Pull request by rdjpalmer**
Remove unused product methods and `listCoffees` query parameters. As per @chrisspang's request

### CODE REVIEW

**Comment by iest** [comment]
Why?

Also don't forget this is a major release change.

**Comment by chrisspang** [comment]
@iest - Going to be doing some refactoring of the Product Catalogue Service (longer term aim to move it into its own service).   These removals will make this easier, while not being critical.  Basically we over-engineered the API as we didn't know what would and wouldn't be useful in the end.  Now we do, and can't see a short/medium term use for these features.

 Nothing to prevent them being added back in in a similar (or newer moar better) way, later.

**Comment by chrisspang** [comment]
Related Viper change: https://github.com/PactCoffee/viper/pull/669

**Comment by chrisspang** [comment]
I've just noticed /v1/products/bundle doesn't even work:

http://pact-swagger.herokuapp.com/#!/products/GET_version_products_bundle_json

```
{
  "errors": {
    "no_method_error": [
      {
        "error": true
      }
    ]
  }
}
```

**Comment by rdjpalmer** [comment]
Spoke to @iest, he's given this a :white_check_mark:. Mergin'

**Pull request merged**
